image: Visual Studio 2017

branches:
    only:
    - master

before_build:
    - nuget restore .\ContainerTests\packages.config -PackagesDirectory ..\packages\
    
platform: Any CPU
configuration: Release

build:
    project: NanoDiCs.sln
    verbosity: minimal