image: Visual Studio 2019

branches:
    only:
    - master

## This is vital for builds to pass. DO NOT CHANGE
before_build:
    - nuget restore .\src\NanoDiCs.sln
    
platform: Any CPU
configuration: Release

build:
    project: .\src\NanoDiCs.sln
    verbosity: minimal