image: Visual Studio 2017

branches:
    only:
    - master

before_build:
    - nuget restore .\src\NanoDiCs.sln
    
platform: Any CPU
configuration: Release

build:
    project: .\src\NanoDiCs.sln
    verbosity: minimal